language: node_js
node_js:
  - "9"
before_script:
  - npm install -g lerna
cache:
  directories:
    - $HOME/.npm
script: 
  - git checkout master
  - lerna bootstrap
  - lerna publish --cd-version major
